INSERT OR REPLACE INTO makes (name, countries) VALUES
  ('ABT', '["DE"]'),
  ('AC', '["GB"]'),
  ('AC Schnitzer', '["DE"]'),
  ('AM General', '["US"]'),
  ('AMC', '["US"]'),
  ('AMG Transport Dynamics', '["US"]'),
  ('APIO', '["JP"]'),
  ('APXGP', '["US"]'),
  ('ARTA', '["JP"]'),
  ('Abarth', '["IT"]'),
  ('Acadian', '["CA"]'),
  ('Acura', '["JP"]'),
  ('Agajanian', '["US"]'),
  ('Alexander Dennis', '["GB"]'),
  ('Alfa Romeo', '["IT"]'),
  ('Alpha Motors', '["US"]'),
  ('AlphaTauri', '["IT"]'),
  ('Alpina', '["DE"]'),
  ('Alpine', '["FR"]'),
  ('American LaFrance', '["US"]'),
  ('Amphicar', '["DE"]'),
  ('Apollo', '["DE"]'),
  ('Argo', '["GB"]'),
  ('Arus', '[]'),
  ('Aston Martin', '["GB"]'),
  ('Auburn', '["US"]'),
  ('Audi', '["DE"]'),
  ('Austin', '["GB"]'),
  ('Austin-Healey', '["GB"]'),
  ('Austro-Daimler', '["AT"]'),
  ('Autech', '["JP"]'),
  ('Autobianchi', '["IT"]'),
  ('Autozam', '["JP"]'),
  ('B Engineering', '["IT"]'),
  ('BAW', '["CN"]'),
  ('BLITZ', '["JP"]'),
  ('BMC', '["GB"]'),
  ('BMW', '["DE"]'),
  ('BRM', '["GB"]'),
  ('BYD', '["CN"]'),
  ('Baojun', '["CN"]'),
  ('Barris Kustom', '["US"]'),
  ('Batman', '["US"]'),
  ('Benetton', '["IT"]'),
  ('Bentley', '["GB"]'),
  ('Bentley Mulliner', '["GB"]'),
  ('Bertone', '["IT"]'),
  ('Bigfoot 4X4', '["US"]'),
  ('Bizzarrini', '["IT"]'),
  ('Blokees', '["CN"]'),
  ('Bobcat', '["CA"]'),
  ('Bollinger', '["US"]'),
  ('Bowler', '["GB"]'),
  ('Brabham', '["AU"]'),
  ('Brabus', '["DE"]'),
  ('Braithwaite', '[]'),
  ('Brightdrop', '["US"]'),
  ('Bugatti', '["FR"]'),
  ('Buick', '["US"]'),
  ('CUPRA', '["ES"]'),
  ('Cadillac', '["US"]'),
  ('Cal State LA', '["US"]'),
  ('Callaway', '["US"]'),
  ('Carmichael', '["GB"]'),
  ('Case', '["US"]'),
  ('Caterham', '["GB"]'),
  ('Chaparral', '["US"]'),
  ('Checker', '["US"]'),
  ('Cheetah', '["US"]'),
  ('Chery', '["CN"]'),
  ('Chevrolet', '["US"]'),
  ('Chevron', '["GB"]'),
  ('Chrysler', '["US"]'),
  ('Citroen', '["FR"]'),
  ('Cizeta', '["IT"]'),
  ('Cord', '["US"]'),
  ('Cunningham', '["US"]'),
  ('Cyberspace', '[]'),
  ('Czinger', '["US"]'),
  ('D-MAX', '["JP"]'),
  ('DAMD', '["JP"]'),
  ('DMC', '["DE"]'),
  ('DS Automobiles', '["FR"]'),
  ('Dacia', '["RO"]'),
  ('Daewoo', '["KR"]'),
  ('Daihatsu', '["JP"]'),
  ('Daimler', '["GB"]'),
  ('Dallara', '["IT"]'),
  ('DarwinPro', '["CN"]'),
  ('Datsun', '["JP"]'),
  ('Dauer', '["DE"]'),
  ('De Tomaso', '["IT"]'),
  ('DeSoto', '["US"]'),
  ('DeltaWing', '["US"]'),
  ('Dennis', '["GB"]'),
  ('Denza', '["CN"]'),
  ('Dino', '["IT"]'),
  ('Disney', '["US"]'),
  ('Divco', '["US"]'),
  ('Dodge', '["US"]')
;

INSERT OR REPLACE INTO makes (name, countries) VALUES
  ('Dome', '["JP"]'),
  ('Dongfeng', '["CN"]'),
  ('Dragon Racing', '["US"]'),
  ('Duesenberg', '["US"]'),
  ('E-ONE', '["US"]'),
  ('Eagle', '["US"]'),
  ('Edsel', '["US"]'),
  ('Efini', '["JP"]'),
  ('Epperly', '["US"]'),
  ('Eunos', '["JP"]'),
  ('Evasive', '["US"]'),
  ('FELD Motorsports', '["US"]'),
  ('FMC', '["US"]'),
  ('FPV', '["AU"]'),
  ('FSO', '["PL"]'),
  ('Farizon', '["CN"]'),
  ('Fast & Furious', '["US"]'),
  ('Ferrari', '["IT"]'),
  ('Fiat', '["IT"]'),
  ('Fisker', '["US"]'),
  ('Foose', '["US"]'),
  ('Ford', '["US"]'),
  ('Forsberg Racing', '["US"]'),
  ('Freeman', '[]'),
  ('Freightliner', '["US"]'),
  ('GAZ', '["RU"]'),
  ('GM', '["US"]'),
  ('GMC', '["US"]'),
  ('GReddy', '["JP"]'),
  ('GWM', '["CN"]'),
  ('Geely', '["CN"]'),
  ('Geely Galaxy', '["CN"]'),
  ('Gemballa', '["DE"]'),
  ('Generic', '[]'),
  ('Genty', '["FR"]'),
  ('Ghe-O', '["RO"]'),
  ('Gordon Murray Automotive', '["GB"]'),
  ('Grumman', '["US"]'),
  ('Gulf', '["US"]'),
  ('Gumpert', '["DE"]'),
  ('Gunther Werks', '["US"]'),
  ('HDT', '["AU"]'),
  ('HKS', '["JP"]'),
  ('HS Schoch', '["DE"]'),
  ('HSV', '["AU"]'),
  ('Haas', '["US"]'),
  ('Haval', '["CN"]'),
  ('Heinz', '["US"]'),
  ('Hennessey', '["US"]'),
  ('HiPhi', '["CN"]'),
  ('Hillman', '["GB"]'),
  ('Hino', '["JP"]'),
  ('Hispano-Suiza', '["ES"]'),
  ('Holden', '["AU"]'),
  ('Honda', '["JP"]'),
  ('Hongqi', '["CN"]'),
  ('Hoonigan', '["US"]'),
  ('Hot Wheels', '["US"]'),
  ('Hudson', '["US"]'),
  ('Hummer', '["US"]'),
  ('Hurst', '["US"]'),
  ('Hymer', '["DE"]'),
  ('Hyundai', '["KR"]'),
  ('IAD', '["GB"]'),
  ('Ikarus', '["HU"]'),
  ('InGen', '["US"]'),
  ('Infiniti', '["JP"]'),
  ('International', '["US"]'),
  ('Isuzu', '["JP"]'),
  ('JLOC', '["JP"]'),
  ('JSDF', '["JP"]'),
  ('Jaguar', '["GB"]'),
  ('Jay Leno', '["US"]'),
  ('Jeep', '["US"]'),
  ('Jetour', '["CN"]'),
  ('Jiefang', '["CN"]'),
  ('Jinbei', '["CN"]'),
  ('Jordan', '["GB"]'),
  ('KTM', '["AT"]'),
  ('Kaiser-Frazer', '["US"]'),
  ('Karma', '["US"]'),
  ('Kawasaki', '["JP"]'),
  ('Kenworth', '["US"]'),
  ('Keyvany', '["AE"]'),
  ('Kia', '["KR"]'),
  ('Kick Sauber', '["CH"]'),
  ('Knight Industries', '["US"]'),
  ('Koenig Specials', '["DE"]'),
  ('Koenigsegg', '["SE"]'),
  ('Krauss-Maffei Wegmann', '["DE"]'),
  ('Kremer', '["DE"]'),
  ('LEGO', '["DK"]'),
  ('LEVC', '["GB"]'),
  ('LTI', '["GB"]'),
  ('Lada', '["RU"]'),
  ('Lamborghini', '["IT"]'),
  ('Lancia', '["IT"]'),
  ('Land Rover', '["GB"]'),
  ('Leapmotor', '["CN"]'),
  ('Lexus', '["JP"]')
;

INSERT OR REPLACE INTO makes (name, countries) VALUES
  ('Leyland', '["GB"]'),
  ('Li', '["CN"]'),
  ('Liberty Walk', '["JP"]'),
  ('Ligier', '["FR"]'),
  ('Lincoln', '["US"]'),
  ('Local Motors', '["US"]'),
  ('Lola', '["GB"]'),
  ('Lotus', '["GB"]'),
  ('Lucid', '["US"]'),
  ('Lynk & Co', '["CN"]'),
  ('MAN', '["DE"]'),
  ('MG', '["CN"]'),
  ('MINI', '["GB"]'),
  ('Mack', '["US"]'),
  ('Mad Mike', '["NZ"]'),
  ('Mahindra', '["IN"]'),
  ('Mansory', '["DE"]'),
  ('Manta', '[]'),
  ('March', '["GB"]'),
  ('Marcos', '["GB"]'),
  ('Maserati', '["IT"]'),
  ('Mastretta', '["MX"]'),
  ('Matchbox', '["GB"]'),
  ('Matra', '["FR"]'),
  ('Matra-Simca', '["FR"]'),
  ('Maxus', '["CN"]'),
  ('Maybach', '["DE"]'),
  ('Mazda', '["JP"]'),
  ('Mazdaspeed', '["JP"]'),
  ('McLaren', '["GB"]'),
  ('Mercedes-AMG', '["DE"]'),
  ('Mercedes-Benz', '["DE"]'),
  ('Mercedes-EQ', '["DE"]'),
  ('Mercedes-McLaren', '["GB"]'),
  ('Mercury', '["US"]'),
  ('Merkur', '["DE"]'),
  ('Meyers', '["US"]'),
  ('Mine''s', '["JP"]'),
  ('Mitsubishi', '["JP"]'),
  ('Mitsubishi Fuso', '["JP"]'),
  ('Mitsui', '["JP"]'),
  ('Mitsuoka', '["JP"]'),
  ('Monarch', '["CA"]'),
  ('Monteverdi', '["CH"]'),
  ('Morgan', '["GB"]'),
  ('Morita', '["JP"]'),
  ('Morris', '["GB"]'),
  ('Mugen', '["JP"]'),
  ('Mygale', '["FR"]'),
  ('NASA', '["US"]'),
  ('NISMO', '["JP"]'),
  ('Nash Motors', '["US"]'),
  ('Navistar', '["US"]'),
  ('Neta', '["CN"]'),
  ('New Holland', '["US"]'),
  ('Nickey', '["US"]'),
  ('Niesmann+Bischoff', '["DE"]'),
  ('Nio', '["CN"]'),
  ('Nissan', '["JP"]'),
  ('Novitec', '["DE"]'),
  ('OSCA', '["IT"]'),
  ('OSI', '["IT"]'),
  ('Oakland', '["US"]'),
  ('Old & New', '[]'),
  ('Oldsmobile', '["US"]'),
  ('Opel', '["DE"]'),
  ('Ora', '["CN"]'),
  ('Oreca', '["FR"]'),
  ('Oscar Meyer', '["US"]'),
  ('Oshkosh', '["US"]'),
  ('PSC Design', '[]'),
  ('Packard', '["US"]'),
  ('Pagani', '["IT"]'),
  ('Pandem', '["JP"]'),
  ('Panoz', '["US"]'),
  ('Patrick Enterprises', '["US"]'),
  ('Peerless', '["GB"]'),
  ('Peugeot', '["FR"]'),
  ('Piaggio', '["IT"]'),
  ('Pierce', '["US"]'),
  ('Pierce-Arrow', '["US"]'),
  ('Pininfarina', '["IT"]'),
  ('Plymouth', '["US"]'),
  ('Polaris', '["US"]'),
  ('Polestar', '["SE"]'),
  ('Pontiac', '["US"]'),
  ('Porsche', '["DE"]'),
  ('Powell', '["US"]'),
  ('Prince', '["JP"]'),
  ('Proton', '["MY"]'),
  ('RAM', '["US"]'),
  ('RE Amemiya', '["JP"]'),
  ('REO', '["US"]'),
  ('RIDOX', '["JP"]'),
  ('RTR', '["US"]'),
  ('RUF', '["DE"]'),
  ('RWB', '["JP"]'),
  ('Racing Bulls', '["IT"]'),
  ('Radar', '[]'),
  ('Radical', '["GB"]')
;

INSERT OR REPLACE INTO makes (name, countries) VALUES
  ('Red Bull Racing', '["AT"]'),
  ('Renault', '["FR"]'),
  ('Renault Sport', '["FR"]'),
  ('Reynard', '["GB"]'),
  ('Rheinmetall', '["DE"]'),
  ('Riley & Scott', '["US"]'),
  ('Rimac', '["HR"]'),
  ('Rivian', '["US"]'),
  ('Roborace', '["GB"]'),
  ('Rocket League', '["US"]'),
  ('Rolls-Royce', '["GB"]'),
  ('Rover', '["GB"]'),
  ('SAIC', '["CN"]'),
  ('SEAT', '["ES"]'),
  ('SRT', '["US"]'),
  ('SSC', '["US"]'),
  ('ST Engineering', '["SG"]'),
  ('Saab', '["SE"]'),
  ('Saleen', '["US"]'),
  ('Saturn', '["US"]'),
  ('Sauber', '["CH"]'),
  ('Scania', '["SE"]'),
  ('Scion', '["JP"]'),
  ('Seagrave', '["US"]'),
  ('Shadow', '["US"]'),
  ('Shelby', '["US"]'),
  ('Simca', '["FR"]'),
  ('Simplex', '["US"]'),
  ('Simpsons', '["US"]'),
  ('Singer', '["US"]'),
  ('Siva', '["GB"]'),
  ('Skoda', '["CZ"]'),
  ('Spark', '["FR"]'),
  ('Speed Racer', '["JP"]'),
  ('Spyker', '["NL"]'),
  ('Statesman', '["AU"]'),
  ('Sterling', '["GB"]'),
  ('Studebaker', '["US"]'),
  ('Stutz', '["US"]'),
  ('Subaru', '["JP"]'),
  ('Sunbeam', '["GB"]'),
  ('Super Aguri', '["JP"]'),
  ('Suzuki', '["JP"]'),
  ('Syd Mead', '["US"]'),
  ('TANK', '["CN"]'),
  ('TOM''S', '["JP"]'),
  ('TRD', '["JP"]'),
  ('TRIGEN Automotive', '[]'),
  ('TVR', '["GB"]'),
  ('Talbot-Lago', '["FR"]'),
  ('Tamiya', '["JP"]'),
  ('Teamsterz', '["GB"]'),
  ('TechnoPark', '["RU"]'),
  ('Teisen', '[]'),
  ('Tesla', '["US"]'),
  ('Textron', '["US"]'),
  ('The Boring Concept', '["US"]'),
  ('Tianjin Xiali', '["CN"]'),
  ('Tokai University', '["JP"]'),
  ('Tomica', '["JP"]'),
  ('Tommykaira', '["JP"]'),
  ('Top Secret', '["JP"]'),
  ('TopCar Design', '["RU"]'),
  ('Toro Rosso', '["IT"]'),
  ('Toyopet', '["JP"]'),
  ('Toyota', '["JP"]'),
  ('Trabant', '["DE"]'),
  ('Triple B', '[]'),
  ('Triumph', '["GB"]'),
  ('Trumpchi', '["CN"]'),
  ('Tucci Engineering', '["US"]'),
  ('Tucker', '["US"]'),
  ('Tyrrell', '["GB"]'),
  ('UAZ', '["RU"]'),
  ('UD Trucks', '["JP"]'),
  ('UNSC', '["US"]'),
  ('URAL', '["RU"]'),
  ('USSV', '["US"]'),
  ('VERTEX', '["JP"]'),
  ('Vauxhall', '["GB"]'),
  ('Vector', '["US"]'),
  ('Vehicle Effects', '["US"]'),
  ('Veilside', '["JP"]'),
  ('Venturi', '["MC"]'),
  ('Volkswagen', '["DE"]'),
  ('Volvo', '["SE"]'),
  ('Voyah', '["CN"]'),
  ('W Motors', '["AE"]'),
  ('Wiesmann', '["DE"]'),
  ('Williams', '["GB"]'),
  ('Willys', '["US"]'),
  ('Wuling', '["CN"]'),
  ('Xiaomi', '["CN"]'),
  ('Xpeng', '["CN"]'),
  ('Yamaha', '["JP"]'),
  ('Yangwang', '["CN"]'),
  ('Yenko', '["US"]'),
  ('ZIS', '["RU"]'),
  ('Zakspeed', '["DE"]'),
  ('Zeekr', '["CN"]')
;

INSERT OR REPLACE INTO makes (name, countries) VALUES
  ('Zender', '["DE"]'),
  ('Zundapp', '["DE"]'),
  ('Zuru', '["NZ"]'),
  ('amuse', '["JP"]'),
  ('iCar', '["CN"]'),
  ('ings', '["JP"]'),
  ('smart', '["DE"]'),
  ('znug design', '["JP"]')
;

