import LeagueShell from '../shared/LeagueShell';
import { EVENT_NAME, EVENT_SHORT, SEASON_LABEL } from './data';
import { crossLeagueById } from '../universeData';
import OverviewTab from './tabs/OverviewTab';
import QualificationTab from './tabs/QualificationTab';
import BracketTab from './tabs/BracketTab';

const meta = {
  name: EVENT_NAME,
  short: EVENT_SHORT,
  seasonLabel: SEASON_LABEL,
  tagline: crossLeagueById.championsLeague.tagline,
  accent: crossLeagueById.championsLeague.accent,
  footerNote: `${EVENT_NAME} is a fictional exhibition. All drivers, ratings, and results are generated by a seeded simulation from each driver's home-league form.`,
};

const tabs = [
  { id: 'overview', label: 'Overview', Component: OverviewTab },
  { id: 'qualification', label: 'Qualification', Component: QualificationTab },
  { id: 'bracket', label: 'Bracket', Component: BracketTab },
];

function ChampionsLeague({ onBack }) {
  return <LeagueShell meta={meta} tabs={tabs} onBack={onBack} />;
}

export default ChampionsLeague;
