import { useEffect, useState } from 'react';
import './shared/League.css';
import './Hub.css';
import { GOVERNING_BODY, LEAGUES, CROSS_LEAGUE_EVENTS } from './universeData';
import { TEAMS as SOLARIS_TEAMS, DRIVERS as SOLARIS_DRIVERS, RACES as SOLARIS_RACES } from './solaris/data';
import { TEAMS as HORIZON_TEAMS, DRIVERS as HORIZON_DRIVERS, RACES as HORIZON_RACES } from './horizon/data';
import { CREWS as RIDGELINE_CREWS, RALLIES as RIDGELINE_RALLIES } from './ridgeline/data';
import { QUALIFIERS as ACL_QUALIFIERS, BRACKET as ACL_BRACKET } from './championsLeague/data';
import { QUALIFIERS as AWC_QUALIFIERS, SQUADS as AWC_SQUADS, ROUNDS_META as AWC_ROUNDS } from './worldCup/data';

const SUMMARIES = {
  solaris: [`${SOLARIS_TEAMS.length} teams`, `${SOLARIS_DRIVERS.length} drivers`, `${SOLARIS_RACES.length} rounds`],
  horizon: [`${HORIZON_TEAMS.length} teams`, `${HORIZON_DRIVERS.length} drivers`, `${HORIZON_RACES.length} rounds`],
  ridgeline: [`${RIDGELINE_CREWS.length} crews`, `${RIDGELINE_CREWS.length * 2} drivers/co-drivers`, `${RIDGELINE_RALLIES.length} rallies`],
  championsLeague: [`${ACL_QUALIFIERS.length} qualifiers`, `${ACL_BRACKET.rounds.length} rounds`, `Champion: ${ACL_BRACKET.champion.name}`],
  worldCup: [`${AWC_QUALIFIERS.length} qualifiers`, `${Object.keys(AWC_SQUADS).length} nations`, `${AWC_ROUNDS.length} rounds`],
};

function HubCard({ item, onSelect }) {
  return (
    <button
      className="rl-hub-card"
      style={{ '--rl-c1': item.accent[0], '--rl-c2': item.accent[1] }}
      onClick={() => onSelect(item.id)}
    >
      <div className="rl-hub-card-bar" />
      <div className="rl-hub-card-body">
        <div className="rl-hub-discipline">{item.discipline}</div>
        <div className="rl-hub-name">{item.name}</div>
        <div className="rl-hub-tagline">{item.tagline}</div>
        <div className="rl-hub-stats">
          {SUMMARIES[item.id].map(s => <span key={s}>{s}</span>)}
        </div>
        <div className="rl-hub-cta">Explore {item.short} →</div>
      </div>
    </button>
  );
}

function Hub({ onSelectLeague }) {
  const [theme, setTheme] = useState(() => localStorage.getItem('theme') || 'dark');

  useEffect(() => {
    document.title = `${GOVERNING_BODY.name} — Fictional Motorsport Universe`;
  }, []);

  useEffect(() => {
    document.documentElement.dataset.theme = theme;
    localStorage.setItem('theme', theme);
  }, [theme]);

  return (
    <div className="rl-page">
      <header className="rl-header rl-hub-header">
        <div className="rl-header-top">
          <a className="rl-back-link" href="/">← Car Collection</a>
          <button className="rl-theme-toggle" onClick={() => setTheme(t => (t === 'dark' ? 'light' : 'dark'))}>
            {theme === 'dark' ? '☀ Light' : '● Dark'}
          </button>
        </div>
        <div className="rl-brand">
          <span className="rl-brand-mark">{GOVERNING_BODY.short}</span>
        </div>
        <h1 className="rl-title">{GOVERNING_BODY.name}</h1>
        <p className="rl-subtitle">{GOVERNING_BODY.blurb}</p>
        <p className="rl-governed-by">Sanctioning body since {GOVERNING_BODY.founded} · {LEAGUES.length} championships · {CROSS_LEAGUE_EVENTS.length} cross-league events</p>
      </header>

      <div className="rl-body">
        <div className="rl-section-title" style={{ marginTop: 8 }}>Championships</div>
        <div className="rl-hub-grid">
          {LEAGUES.map(league => <HubCard key={league.id} item={league} onSelect={onSelectLeague} />)}
        </div>

        <div className="rl-section-title">Cross-league competitions</div>
        <p className="rl-lede" style={{ marginTop: -6 }}>
          Drivers qualify for these based on their standing at the end of the season in their
          home league — see each event's Qualification or Squads tab for the exact rule.
        </p>
        <div className="rl-hub-grid">
          {CROSS_LEAGUE_EVENTS.map(event => <HubCard key={event.id} item={event} onSelect={onSelectLeague} />)}
        </div>

        <div className="rl-footer">
          Every league, team, driver, and result on these pages is fictional and generated by
          a seeded simulation for illustration.
        </div>
      </div>
    </div>
  );
}

export default Hub;
