// Performance class + stats, loaded from the optional static file
// public/car_stats.json (generated by stats_draft/finalize.py).

export const CLASS_ORDER = ['E', 'D', 'C', 'B', 'A', 'S', 'X', 'U'];

// Forza-style class colours; U is "unrated".
export const CLASS_COLORS = {
  E: '#8a8f98', D: '#2bb3a8', C: '#e8c11c', B: '#f28c1c', A: '#e03a3a', S: '#8c4fd6', X: '#3ec46d', U: '#b0b0b0',
};
// Text colour that reads on each class colour.
export const CLASS_TEXT = { E: '#fff', D: '#fff', C: '#1a1a1a', B: '#fff', A: '#fff', S: '#fff', X: '#0f2d1a', U: '#333' };

export const CLASS_LABELS = {
  E: 'E class', D: 'D class', C: 'C class', B: 'B class', A: 'A class', S: 'S class', X: 'X class', U: 'Unrated',
};

// Must match stats_draft/prepare.py: trimmed Make|Model|Year.
export const statsKeyFor = (car) =>
  `${String(car.Make || '').trim()}|${String(car.Model || '').trim()}|${String(car.Year || '').trim()}`;

// Bars shown in the Stats tab. Top speed is a real km/h figure; the rest are
// scores where 100 is the stock ceiling but, Asphalt-style, values may run
// past it. `max` is the bar/slider scale, `stock` the marker for the stock
// ceiling.
export const STAT_FIELDS = [
  { key: 'ts', label: 'Top Speed', max: 650, stock: 400, step: 0.1, unit: ' km/h', color: '#3b82f6' },
  { key: 'ha', label: 'Handling', max: 150, stock: 100, step: 0.1, color: '#2bb3a8' },
  { key: 'ac', label: 'Acceleration', max: 150, stock: 100, step: 0.1, color: '#e03a3a' },
  { key: 'ni', label: 'Nitro', max: 150, stock: 100, step: 0.1, color: '#f28c1c' },
  { key: 'st', label: 'Strength', max: 150, stock: 100, step: 0.1, color: '#8c4fd6' },
  // Off-road ability. 0 means "not applicable": hidden outside edit mode and
  // excluded from the class percentiles.
  { key: 'cr', label: 'Crossing', max: 150, stock: 100, step: 0.1, color: '#a0522d', hideWhenZero: true },
];

// Display helper: one decimal, no trailing ".0" noise for whole numbers.
export const fmtStat = (v) => { const n = Number(v) || 0; return Number.isInteger(n) ? String(n) : n.toFixed(1); };

// Same formula as stats_draft/finalize.py, so a live edit shows the rating the
// draft pipeline would produce. Uncapped. Each stat runs through a convex
// curve (exponent 1.6) so top-end points are worth more than low ones;
// strength is linear, centred on 50, and deliberately the lightest weight.
const CURVE = 1.6;
const curve = (v) => 100 * Math.pow(Math.max(v, 0) / 100, CURVE);
// 100 km/h -> 0, 400 km/h -> 100; only 30% credit beyond that.
const speedScore = (ts) => { const s = (ts - 100) / 3; return s <= 100 ? s : 100 + (s - 100) * 0.3; };

// Crossing stands in for handling off the tarmac: worth most to a car that
// handles poorly on it, least to one that already handles well.
const crossingFactor = (ha) => Math.max(0.4, Math.min(1, 1 - ha / 220));

export const computeRating = ({ ts, ac, ha, ni, st, cr = 0 }) => {
  const speed = speedScore(ts);
  const extremity = Math.max(0, (st - 50) * (Math.max(0, Math.min(100, speed)) - 50)) / 2500;
  const wSt = 2 + 4 * extremity;
  return Math.round(8 * curve(speed) + 12 * curve(ac) + 15 * curve(ha) + 8 * curve(ni)
    + 13 * crossingFactor(ha) * curve(cr || 0) + wSt * (st - 50) + 150);
};

export const ARCHETYPE_ORDER = ['speed', 'nitro', 'grip', 'launch', 'brawler', 'balanced'];
export const ARCHETYPE_LABELS = {
  speed: 'Top-end', nitro: 'Nitro-heavy', grip: 'Grip specialist', launch: 'Launcher', brawler: 'Brawler', balanced: 'Balanced',
};

// Mirrors EFFECTS + NITRO_OFFSET in stats_draft/archetypes.py: how each
// archetype bends a neutral stat line. ts is a fraction, the rest are points.
const ARCHETYPE_EFFECTS = {
  speed:    { ts: +0.06, ac: -3, ha: -3, st: 0,  ni: -16 },
  nitro:    { ts: -0.02, ac: +3, ha: -4, st: 0,  ni: +34 },
  grip:     { ts: -0.03, ac: 0,  ha: +8, st: -2, ni: -14 },
  launch:   { ts: -0.04, ac: +8, ha: -2, st: +2, ni: +12 },
  brawler:  { ts: -0.02, ac: 0,  ha: -5, st: +8, ni: +6 },
  balanced: { ts: 0,     ac: 0,  ha: 0,  st: 0,  ni: 0 },
};
const NITRO_BASE = 50;
const STAT_CAP = 150;

// Small deterministic PRNG so a given seed always yields the same suggestion.
const mulberry32 = (seed) => () => {
  seed = (seed + 0x6D2B79F5) | 0;
  let t = Math.imul(seed ^ (seed >>> 15), 1 | seed);
  t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
  return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
};

// Propose a stat line for a class + archetype that lands on `target` rating.
// `profile` is the class's typical line (median ts/ac/ha/st). The archetype
// bends it and a seeded jitter gives each suggestion its own character; then
// a single scale factor is solved by bisection so the formula hits the target:
// speed score, acceleration and handling scale linearly, nitro by the square
// root (it is character, not class), strength stays put (least important).
// Crossing is kept as given so off-road cars keep their off-road credit.
export function suggestStats({ arch, target, profile, cr = 0, seed = 1 }) {
  const e = ARCHETYPE_EFFECTS[arch] || ARCHETYPE_EFFECTS.balanced;
  const rnd = mulberry32(seed);
  const j = (amp) => (rnd() * 2 - 1) * amp;
  const base = {
    ts: Math.max(110, profile.ts * (1 + e.ts) * (1 + j(0.03))),
    ac: Math.max(1, profile.ac + e.ac + j(4)),
    ha: Math.max(1, profile.ha + e.ha + j(4)),
    ni: Math.max(5, NITRO_BASE + e.ni + j(14)),
    st: Math.max(0, Math.min(STAT_CAP, profile.st + e.st + j(5))),
  };
  const cap = (v) => Math.max(0, Math.min(STAT_CAP, v));
  const build = (k) => ({
    ts: 100 + (base.ts - 100) * k,
    ac: cap(base.ac * k),
    ha: cap(base.ha * k),
    ni: cap(Math.max(5, base.ni * Math.sqrt(k))),
    st: base.st,
    cr: cr || 0,
  });
  let lo = 0.02, hi = 5;
  for (let i = 0; i < 48; i++) { const mid = (lo + hi) / 2; if (computeRating(build(mid)) < target) lo = mid; else hi = mid; }
  const s = build((lo + hi) / 2);
  const out = {};
  for (const k of ['ts', 'ac', 'ha', 'ni', 'st']) out[k] = Math.round(s[k] * 10) / 10;
  return out;
}
