import LeagueShell from '../shared/LeagueShell';
import { LEAGUE_NAME, LEAGUE_SHORT, SEASON_LABEL } from './data';
import { leagueById } from '../universeData';
import OverviewTab from './tabs/OverviewTab';
import TeamsTab from './tabs/TeamsTab';
import CalendarTab from './tabs/CalendarTab';
import StandingsTab from './tabs/StandingsTab';
import PointsTab from './tabs/PointsTab';

const meta = {
  name: LEAGUE_NAME,
  short: LEAGUE_SHORT,
  seasonLabel: SEASON_LABEL,
  tagline: leagueById.solaris.tagline,
  accent: leagueById.solaris.accent,
  footerNote: `${LEAGUE_NAME} and all teams, drivers, and circuits are fictional. Results are generated by a seeded simulation from each team's pace and each driver's skill rating.`,
};

const tabs = [
  { id: 'overview', label: 'Overview', Component: OverviewTab },
  { id: 'teams', label: 'Teams & Drivers', Component: TeamsTab },
  { id: 'calendar', label: 'Calendar', Component: CalendarTab },
  { id: 'standings', label: 'Standings', Component: StandingsTab },
  { id: 'points', label: 'Points System', Component: PointsTab },
];

function SolarisLeague({ onBack }) {
  return <LeagueShell meta={meta} tabs={tabs} onBack={onBack} />;
}

export default SolarisLeague;
