import LeagueShell from '../shared/LeagueShell';
import { EVENT_NAME, EVENT_SHORT, SEASON_LABEL } from './data';
import { crossLeagueById } from '../universeData';
import OverviewTab from './tabs/OverviewTab';
import SquadsTab from './tabs/SquadsTab';
import ScheduleTab from './tabs/ScheduleTab';
import StandingsTab from './tabs/StandingsTab';

const meta = {
  name: EVENT_NAME,
  short: EVENT_SHORT,
  seasonLabel: SEASON_LABEL,
  tagline: crossLeagueById.worldCup.tagline,
  accent: crossLeagueById.worldCup.accent,
  footerNote: `${EVENT_NAME} is a fictional exhibition. All squads, ratings, and results are generated by a seeded simulation from each driver's home-league form.`,
};

const tabs = [
  { id: 'overview', label: 'Overview', Component: OverviewTab },
  { id: 'squads', label: 'Squads', Component: SquadsTab },
  { id: 'schedule', label: 'Schedule', Component: ScheduleTab },
  { id: 'standings', label: 'Standings', Component: StandingsTab },
];

function WorldCup({ onBack }) {
  return <LeagueShell meta={meta} tabs={tabs} onBack={onBack} />;
}

export default WorldCup;
