import LeagueShell from '../shared/LeagueShell';
import { LEAGUE_NAME, LEAGUE_SHORT, SEASON_LABEL } from './data';
import { leagueById } from '../universeData';
import OverviewTab from './tabs/OverviewTab';
import TeamsTab from './tabs/TeamsTab';
import CalendarTab from './tabs/CalendarTab';
import StandingsTab from './tabs/StandingsTab';
import FormatTab from './tabs/FormatTab';

const meta = {
  name: LEAGUE_NAME,
  short: LEAGUE_SHORT,
  seasonLabel: SEASON_LABEL,
  tagline: leagueById.horizon.tagline,
  accent: leagueById.horizon.accent,
  footerNote: `${LEAGUE_NAME} and all teams, drivers, and circuits are fictional. Results are generated by a seeded simulation from each team's pace and driver squad ratings.`,
};

const tabs = [
  { id: 'overview', label: 'Overview', Component: OverviewTab },
  { id: 'teams', label: 'Teams & Squads', Component: TeamsTab },
  { id: 'calendar', label: 'Calendar', Component: CalendarTab },
  { id: 'standings', label: 'Standings', Component: StandingsTab },
  { id: 'format', label: 'Format & Points', Component: FormatTab },
];

function HorizonLeague({ onBack }) {
  return <LeagueShell meta={meta} tabs={tabs} onBack={onBack} />;
}

export default HorizonLeague;
